<a href="https://colab.research.google.com/github/shreyasgowdac-319/ML-LAB/blob/main/1BM23CS319_Lab_6_Decision_Tree_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from google.colab import files
uploaded = files.upload()



print("---- IRIS DATASET ----")

iris = pd.read_csv("iris (1) - iris (1) (1).csv")

X_iris = iris.drop("species", axis=1)
y_iris = iris["species"]

X_train_i, X_test_i, y_train_i, y_test_i = train_test_split(
    X_iris, y_iris, test_size=0.2, random_state=42
)

iris_model = DecisionTreeClassifier()

iris_model.fit(X_train_i, y_train_i)

y_pred_i = iris_model.predict(X_test_i)

iris_accuracy = accuracy_score(y_test_i, y_pred_i)
print("Accuracy:", iris_accuracy)

print("Confusion Matrix:")
print(confusion_matrix(y_test_i, y_pred_i))




print("\n---- DRUG DATASET ----")

drug = pd.read_csv("drug - drug.csv")

le = LabelEncoder()
for column in drug.columns:
    drug[column] = le.fit_transform(drug[column])

X_drug = drug.drop("Drug", axis=1)
y_drug = drug["Drug"]

X_train_d, X_test_d, y_train_d, y_test_d = train_test_split(
    X_drug, y_drug, test_size=0.2, random_state=42
)


drug_model = DecisionTreeClassifier()


drug_model.fit(X_train_d, y_train_d)


y_pred_d = drug_model.predict(X_test_d)


drug_accuracy = accuracy_score(y_test_d, y_pred_d)
print("Accuracy:", drug_accuracy)


print("Confusion Matrix:")
print(confusion_matrix(y_test_d, y_pred_d))

Saving iris (1) - iris (1) (1).csv to iris (1) - iris (1) (1) (4).csv
---- IRIS DATASET ----
Accuracy: 1.0
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

---- DRUG DATASET ----
Accuracy: 1.0
Confusion Matrix:
[[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]


In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("petrol_consumption - petrol_consumption.csv")

print(data.head())

X = data.drop("Petrol_Consumption", axis=1)
y = data["Petrol_Consumption"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = DecisionTreeRegressor()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)

Saving petrol_consumption - petrol_consumption.csv to petrol_consumption - petrol_consumption (3).csv
   Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410  
Mean Absolute Error: 94.3
Mean Squared Error: 17347.7
Root Mean Squared Error: 131.7106677532234
